name: homework5
description: Random Images
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  redux_epics: ^0.15.0
  redux: ^5.0.0
  rxdart: ^0.27.7
  flutter_redux: ^0.10.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true